name: CI Build and Release

# ДОДАЙ ЦЕЙ БЛОК ПРЯМО ТУТ:
permissions:
  contents: write

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show author info
        run: |
          echo "Maks Shilo"
          git log -1 --pretty=format:"%an <%ae>"

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build project
        working-directory: ./Calendar
        run: |
          mkdir ../build
          # Додано gdi32.lib
          cl /EHsc /DUNICODE /D_UNICODE *.cpp user32.lib gdi32.lib /Fe:../build/CalendarApp.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto-release-${{ github.run_number }}
          name: Auto Release ${{ github.run_number }}
          files: build/CalendarApp.exe     # <--- Додай це, щоб .exe файл прикріпився до релізу!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}